[package]
name = "onitama"
description="A library for Onitama game"
version = "0.1.2"
authors = ["Hannes Karppila <hannes.karppila@gmail.com>"]
license = "MIT"
repository="https://github.com/Dentosal/onitama-rs"


[dependencies]
lazy_static = "0.2"
